name: Converted Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
          
      - name: Install Compose
        uses: ndeloof/install-docker-compose@v0.0.1
        with:
          version: latest # defaults to 'latest'
          legacy: true
          
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Getting Docker Files
        run: |
          wget
          https://raw.githubusercontent.com/authorjapps/zerocode-docker-factory/master/compose/kafka-schema-registry.yml
      - name: Running Kafka 
        run: docker-compose -f kafka-schema-registry.yml up -d && sleep 10
      
      - name: Build with Maven
        run: mvn clean test
